// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSikaYGrh6OJpCAfpOYk3hQtzNwA86lKw',
    appId: '1:53730538511:ios:0ad99d38605d0d48a8df7a',
    messagingSenderId: '53730538511',
    projectId: 'student-learning-ms',
    storageBucket: 'student-learning-ms.firebasestorage.app',
    iosBundleId: 'com.example.studentLms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTJivy09RtLPWRLhXLVssZ4KYjBdF8QvM',
    appId: '1:53730538511:web:2aeedceeab739e4ea8df7a',
    messagingSenderId: '53730538511',
    projectId: 'student-learning-ms',
    authDomain: 'student-learning-ms.firebaseapp.com',
    storageBucket: 'student-learning-ms.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc1ctNa42utARNb_Q8BxEEr_jh9014EV8',
    appId: '1:53730538511:android:b8db8b9e28106141a8df7a',
    messagingSenderId: '53730538511',
    projectId: 'student-learning-ms',
    storageBucket: 'student-learning-ms.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTJivy09RtLPWRLhXLVssZ4KYjBdF8QvM',
    appId: '1:53730538511:web:2aeedceeab739e4ea8df7a',
    messagingSenderId: '53730538511',
    projectId: 'student-learning-ms',
    authDomain: 'student-learning-ms.firebaseapp.com',
    storageBucket: 'student-learning-ms.firebasestorage.app',
  );

}